name: deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: install ssh key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
            ${{ secrets.SSH_KEY_DEV1 }}

      - name: cd
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          set -e
          cd /root/bots/s21_bot || exit 1
          echo "Боту араарабын"
          sudo systemctl stop s21_bot || echo "Бот то5о эрэ улэлээн буппэтэ"
          echo "Пулли гынабын..."
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git fetch --all
          git reset --hard origin/main
          echo "Виртуальнай окруженияны обновляйдыыбын..."
          python3 -m venv .venv --updgrade
          source .venv/bin/activate
          pip install -r requirements.txt --updgrade
          echo "Боту холбуубун"
          sudo systemctl start s21_bot
          echo "Барыта учугэй"
          EOF
