name: deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: install ssh key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
            ${{ secrets.SSH_KEY_DEV1 }}

      - name: cd
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          set -e
          cd /root/bots/s21_bot || exit 1
          echo "Боту араарабын"
          kill $(cat /root/bots/s21_bot/bot.pid) 2>/dev/null || true
          echo "Пулли гынабын..."
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git fetch --all
          git reset --hard origin/main
          echo "Виртуальнай окруженияны обновляйдыыбын..."
          python3 -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
          echo "Боту холбуубун"
          nohup .venv/bin/python -u main.py > bot.log 2>&1 &
          echo $! > bot.pid
          echo "Барыта учугэй"
          EOF
