name: deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Prepare .env file
        run: |
          echo "TOKEN=${{ secrets.TOKEN }}" > .env
          echo "MAIN_ADMIN_ID=${{ secrets.MAIN_ADMIN_ID }}" >> .env
          echo "GOOGLE_SHEETS_CREDS=google_creds.json" >> .env
          echo "SPREADSHEET_KEY=${{ secrets.SPREADSHEET_KEY }}" >> .env
          echo "login_token=${{ secrets.login_token }}" >> .env
          echo "password_token=${{ secrets.password_token }}" >> .env

      - name: Prepare service account file
        env:
          GOOGLE_CREDS_JSON: ${{ secrets.GOOGLE_CREDS_JSON }}
        run: |
          echo "$GOOGLE_CREDS_JSON" > google_creds.json

      - name: Copy files to server
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_2 }}
          source: "."
          target: "/root/bots/s21_bot"

      - name: Restart s21_bot service
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY_2 }}
          script: |
            cd /root/bots/s21_bot
            pip install -r requirements.txt
            sudo systemctl restart s21_bot.service
